# Generated by Django 4.2.11 on 2024-03-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lightningconfigurations_remove_light_brightness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightningconfigurations',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
