# Generated by Django 4.2.11 on 2024-03-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_home_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='configurations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lightsconfig', to='core.lightningconfigurations'),
        ),
    ]
