# Generated by Django 4.2.11 on 2024-03-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_light_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningconfigurations',
            name='theme',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
