# Generated by Django 4.2.11 on 2024-03-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lightningconfigurations_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningScenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='lightningconfigurations',
            name='theme',
        ),
    ]
