# Generated by Django 4.2.11 on 2024-03-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lightningscenes_remove_lightningconfigurations_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='configurations',
        ),
        migrations.AddField(
            model_name='lightningconfigurations',
            name='light',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='core.light'),
        ),
    ]
