# Generated by Django 4.2.11 on 2024-03-10 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_light_configurations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningconfigurations',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='core.lightningscenes'),
        ),
    ]
